trigger:
  branches:
    include: 
      - master
  paths:
    include:
    - 'src/*'

stages:

  - stage: publish
    displayName: 'Publish'
    dependsOn: [  ]
    pool:
      vmImage: 'windows-latest'
    jobs:

      - job: publish
        displayName: 'Publish'
        dependsOn: [ ]
        steps:

          - task: Cache@2
            displayName: 'Cache: nuke-temp'
            inputs:
              key: $(Agent.OS) | nuke-temp | **/global.json, **/*.csproj, **/Directory.Packages.props
              restoreKeys: $(Agent.OS) | nuke-temp
              path: .nuke/temp
          - task: Cache@2
            displayName: 'Cache: nuget-packages'
            inputs:
              key: $(Agent.OS) | nuget-packages | **/global.json, **/*.csproj, **/Directory.Packages.props
              restoreKeys: $(Agent.OS) | nuget-packages
              path: $(USERPROFILE)/.nuget/packages
          - task: CmdLine@2
            displayName: 'Nuke: Publish'
            inputs:
              script: './build.cmd Publish'
            env:
              NuGetApiKey: $(NuGetApiKey)
          - task: PublishBuildArtifacts@1
            displayName: 'Publish: artifacts'
            inputs:
              pathToPublish: './artifacts'
              artifactName: artifacts